### ISSUE TITLE
Support Parallels

### ISSUE THREAD

**Issue by jhgorse** [jlduran/packer-FreeBSD#34]
I forked and got Parallels working for a FreeBSD 13.3 vm. Here are the commits:
https://github.com/jhgorse/packer-FreeBSD/pull/1/commits

Sadly Parallels does not seem to have guest VM tools for *BSD, so that needed disabled.

I thought about adding a quick check in the script to find the latest dated file for a given series. It would be nice to say 13.3 STABLE and the builder does the rest.

Let me know if you'd like to have Parallels and I can work up a PR for it.

Cheers,
Joe

**Comment by jlduran** [comment]
> I forked and got Parallels working for a FreeBSD 13.3 vm. Here are the commits: https://github.com/jhgorse/packer-FreeBSD/pull/1/commits

I left a review there, if you want to submit it here.


> Sadly Parallels does not seem to have guest VM tools for *BSD, so that needed disabled.

No problem, the switch should have an empty case that does nothing if it is for Parallels.

> I thought about adding a quick check in the script to find the latest dated file for a given series. It would be nice to say 13.3 STABLE and the builder does the rest.

Yes, you can keep this file for your repo only, since we use a GitHub action for testing, and Parallels is not available.
